"""Command-line interface for Agent Infrastructure Platform."""

from __future__ import annotations

import asyncio
import json
import sys
from typing import Any

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.tree import Tree

app = typer.Typer(
    name="aip",
    help="Agent Infrastructure Platform CLI",
    rich_markup_mode="rich",
)
console = Console()


@app.command()
def version():
    """Show version information."""
    from agent_infrastructure_platform import __version__
    console.print(f"Agent Infrastructure Platform [bold blue]v{__version__}[/bold blue]")


@app.command()
def init(
    path: str = typer.Option(".", "--path", "-p", help="Project path"),
):
    """Initialize a new AIP project."""
    console.print(Panel.fit(
        "[bold green]Initializing Agent Infrastructure Platform Project[/bold green]",
    ))
    
    # Create project structure
    import os
    
    dirs = [
        f"{path}/agents",
        f"{path}/protocols",
        f"{path}/policies",
        f"{path}/workflows",
        f"{path}/tests",
    ]
    
    for d in dirs:
        os.makedirs(d, exist_ok=True)
        console.print(f"  Created: {d}")
    
    # Create default config
    config = {
        "project": {
            "name": "my-agent-project",
            "version": "1.0.0",
        },
        "agents": {
            "default_timeout": 300,
            "max_concurrent": 100,
        },
        "protocols": ["mcp", "a2a", "acp"],
        "governance": {
            "audit_enabled": True,
            "policy_check": True,
        },
    }
    
    config_path = f"{path}/aip.yaml"
    import yaml
    with open(config_path, "w") as f:
        yaml.dump(config, f)
    
    console.print(f"  Created: {config_path}")
    console.print()
    console.print("[green]✓ Project initialized successfully![/green]")


@app.command()
def agent_list(
    registry: str = typer.Option("http://localhost:8000", "--registry", "-r"),
):
    """List registered agents."""
    table = Table(title="Registered Agents")
    table.add_column("ID", style="cyan")
    table.add_column("Name", style="green")
    table.add_column("Status", style="yellow")
    table.add_column("Capabilities", style="blue")
    
    # Example data - would fetch from registry
    table.add_row(
        "agent-1a2b3c",
        "research-agent",
        "[green]active[/green]",
        "web-research, data-analysis",
    )
    table.add_row(
        "agent-4d5e6f",
        "writing-agent",
        "[green]active[/green]",
        "content-writing, editing",
    )
    
    console.print(table)


@app.command()
def agent_create(
    name: str = typer.Argument(..., help="Agent name"),
    capabilities: str = typer.Option(
        "",
        "--capabilities",
        "-c",
        help="Comma-separated capabilities",
    ),
):
    """Create a new agent."""
    console.print(Panel.fit(
        f"[bold]Creating Agent: {name}[/bold]",
    ))
    
    caps = [c.strip() for c in capabilities.split(",") if c.strip()]
    
    console.print(f"Capabilities: {', '.join(caps)}")
    
    # Generate agent template
    agent_code = f'''"""
{name} Agent - Generated by AIP CLI
"""

from agent_infrastructure_platform import Agent
from agent_infrastructure_platform.common.agent import AgentConfig
from agent_infrastructure_platform.common.types import Context, Task


class {name.replace("-", "_").title()}Agent(Agent):
    """Agent implementation."""

    def __init__(self):
        super().__init__(AgentConfig(name="{name}"))
        
        # Register capabilities
{chr(10).join(f"        self.register_capability(Capability(name="{c}", category=CapabilityCategory.TOOL))" for c in caps) if caps else "        pass"}

    async def handle_task(self, task: Task, ctx: Context) -> Task:
        """Handle incoming tasks."""
        # TODO: Implement task handling
        task.output_data = {{"result": "Task completed"}}
        return task

    async def handle_message(self, message, ctx):
        """Handle incoming messages."""
        return None


if __name__ == "__main__":
    import asyncio
    
    agent = {name.replace("-", "_").title()}Agent()
    asyncio.run(agent.initialize())
'''
    
    filename = f"agents/{name}.py"
    with open(filename, "w") as f:
        f.write(agent_code)
    
    console.print(f"[green]✓ Created agent: {filename}[/green]")


@app.command()
def serve(
    host: str = typer.Option("0.0.0.0", "--host", "-h"),
    port: int = typer.Option(8000, "--port", "-p"),
    protocol: str = typer.Option("mcp", "--protocol", help="Protocol to serve"),
):
    """Start an AIP server."""
    console.print(Panel.fit(
        f"[bold]Starting AIP Server[/bold]\n"
        f"Protocol: {protocol}\n"
        f"Address: {host}:{port}",
    ))
    
    async def run_server():
        if protocol == "mcp":
            from agent_infrastructure_platform.protocols.mcp.server import MCPServer
            from agent_infrastructure_platform.protocols.mcp.types import MCPServerCapabilities
            
            server = MCPServer(
                name="aip-mcp-server",
                capabilities=MCPServerCapabilities(tools=True, resources=True),
                host=host,
                port=port,
            )
            
            # Register example tools
            @server.tool("echo", description="Echo a message back")
            async def echo(message: str) -> str:
                return message
            
            await server.start()
        
        elif protocol == "a2a":
            from agent_infrastructure_platform.protocols.a2a.protocol import A2AProtocol
            from agent_infrastructure_platform.protocols.a2a.types import AgentCard
            
            agent_card = AgentCard(
                name="aip-a2a-agent",
                url=f"http://{host}:{port}",
            )
            
            a2a = A2AProtocol(agent_card, host=host, port=port)
            
            @a2a.on_task
            async def handle_task(task):
                # Echo task back
                from agent_infrastructure_platform.protocols.a2a.types import TaskState, TaskStatus
                task.status = TaskStatus(state=TaskState.COMPLETED)
                return task
            
            await a2a.start_server()
    
    asyncio.run(run_server())


@app.command()
def status(
    registry: str = typer.Option("http://localhost:8000", "--registry", "-r"),
):
    """Show platform status."""
    tree = Tree("[bold blue]Agent Infrastructure Platform[/bold blue]")
    
    # Protocols
    protocols = tree.add("[yellow]Protocols[/yellow]")
    protocols.add("[green]✓[/green] MCP (Model Context Protocol)")
    protocols.add("[green]✓[/green] A2A (Agent-to-Agent)")
    protocols.add("[green]✓[/green] ACP (Agent Communication)")
    protocols.add("[green]✓[/green] ANP (Agent Network)")
    
    # Infrastructure
    infra = tree.add("[yellow]Infrastructure[/yellow]")
    infra.add("[green]✓[/green] Identity & Trust")
    infra.add("[green]✓[/green] Memory & State")
    infra.add("[green]✓[/green] Orchestration")
    infra.add("[green]✓[/green] Governance")
    
    # Agents
    agents = tree.add("[yellow]Agents[/yellow]")
    agents.add("research-agent [dim]active[/dim]")
    agents.add("writing-agent [dim]active[/dim]")
    agents.add("review-agent [dim]idle[/dim]")
    
    console.print(tree)


@app.command()
def policy_check(
    policy_file: str = typer.Argument(..., help="Policy file to check"),
):
    """Validate a policy file."""
    console.print(f"Checking policy file: {policy_file}")
    
    try:
        with open(policy_file) as f:
            import yaml
            policy = yaml.safe_load(f)
        
        console.print("[green]✓ Policy file is valid[/green]")
        
        # Display policy
        console.print_json(json.dumps(policy, indent=2))
        
    except Exception as e:
        console.print(f"[red]✗ Error: {e}[/red]")
        raise typer.Exit(1)


def main():
    """Entry point for CLI."""
    app()


if __name__ == "__main__":
    main()
